server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:blog.db
    username:
    password:
  jpa:
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

