server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:blog.db
    username:
    password:
  jpa:
    database-platform: com.daishuaiqing.blog.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    #打印SQL信息
    com.daishuaiqing.blog.mapper: debug
